apiVersion: v1
kind: Service
metadata:
  name: hello-service-nodeport
  namespace: Subhadeep
spec:
  type: NodePort
  selector:
    app: hello-service
  ports:
  - port: 3001
    targetPort: 3001
    

